name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Generate the snake
      - uses: Platane/snk@v2.0.0
        with:
          github_user_name: hasanaliozkan-dev
          output: dist/github-contribution-grid-snake.svg

      # Show status (optional debugging step)
      - run: git status

      # Commit and push changes
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated snake contribution graph" || echo "No changes to commit"
          git push origin main
